---
title: "Анализ заболеваемости Covid19 в России, относительно стран соседей"
output: 
  word_document: 
    highlight: haddock
    fig_width: 8
    fig_height: 8
    fig_caption: yes
    keep_md: yes
---

```{r setup, echo = FALSE}
# Загрузка всех данных и импорт данных в проект и библиотеки ------------------

libraries = c("tidyverse", "openxlsx",
              "dplyr", "tidyr", "stringr",
              "ggplot2", "forecast",
              "openxlsx", "quantreg")

#' Downloading and installing packages in R session
#'
#' @param libs - vector of character libraries that you want to download
#'
#' @return NULL
#' @export
#'
#' @examples
#' install_new_package("ggplot2")
#' install_new_package(c("dplyr", "forecast"))
install_new_package <- function(libs = libraries) {
    for (libI in libs) {
        if (libI %in% installed.packages() == FALSE) {
            install.packages(libI)
        }
    }
}

install_new_package(libs = libraries)

if (!dir.exists("./output_pngs/")) {
  dir.create("./output_pngs")
}


if (!dir.exists("./output_pngs/World")) {
  dir.create("./output_pngs/World")
}
# Подключение пакетов -----------------------------------------------------
library(dplyr)    # Обработка фреймов
library(tidyr)    # Пакет для приведения данных в порядок
library(stringr)  # Пакет для обработки строк
library(openxlsx) # Пакет для экспорта данных в xlsx

# Загрузка данных ---------------------------------------------------------
df <- read.csv(file = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
cat("\nConfid data downloaded!\n")
df_deaths <- read.csv(file = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")
cat("\nDeaths data downloaded\n")
df_recovered <- read.csv(file = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")
cat("\nRecovered data downloaded\n")
# Исследование данных -----------------------------------------------------

# Имена столбцов показывают, что данные о Covid19 обновляются путём добавления
# столбцов каждый день
#
# Строк 273, что соответствует локациям, в которых проводятся подсчёты
# статистики числа заболевших
#
# О странах известно, в каких точных (до второго знака)
# координатах они находятся
#
# Типы полей - целочисленные


# Слияние колонок страна/регион -------------------------------------------

# Создадим новую колонку из двух старых
df <- tidyr::unite(data = df,
                   col = "Country/Province",
                   sep = "/",
                   Country.Region,
                   Province.State)
df_deaths <- tidyr::unite(data = df_deaths,
                          col = "Country/Province",
                          sep = "/",
                          Country.Region,
                          Province.State)
df_recovered <- tidyr::unite(data = df_recovered,
                             col = "Country/Province",
                             sep = "/",
                             Country.Region,
                             Province.State)

# Создание дополнительного фрейма данных с метаданными о странах ----------

#“Страна/Регион”
#Широта
#Долгота
#Сумма заболевших
#Среднее число заболевших
#Стандартное отклонение числа заболевших

# Сохраним названия в отдельный вектор
country_names <- df$`Country/Province`
country_names_deaths <- df_deaths$`Country/Province`
country_names_recovered <- df_recovered$`Country/Province`

# Сохраним даты в отдельный вектор
test_dates <- colnames(df)[4:ncol(df)]

# Сохраним в отдельный df информацию о странах и описательные статистики
df_meta <- data.frame(df[, 1:3],
                      pos_mean = apply(as.matrix(df[, 4:ncol(df)]), 1, mean),
                      pos_std = apply(as.matrix(df[, 4:ncol(df)]), 1, mean),
                      pos_sum = apply(as.matrix(df[, 4:ncol(df)]), 1, sum))
df_deaths_meta <- data.frame(df_deaths[, 1:3],
                             pos_mean = apply(as.matrix(df[, 4:ncol(df)]), 1, mean),
                             pos_std = apply(as.matrix(df[, 4:ncol(df)]), 1, mean),
                             pos_sum = apply(as.matrix(df[, 4:ncol(df)]), 1, sum))
df_recovered_meta <- data.frame(df[, 1:3],
                                pos_mean = apply(as.matrix(df[, 4:ncol(df)]), 1, mean),
                                pos_std = apply(as.matrix(df[, 4:ncol(df)]), 1, mean),
                                pos_sum = apply(as.matrix(df[, 4:ncol(df)]), 1, sum))


# Создание нового фрейма --------------------------------------------------

# 1. Обработка дат для приведения их к стандартному формату

# Избавимся от лишних символов
test_dates <- gsub("X", "", test_dates)

# Вытащим из вектора дат месяцы, дни и годы
months <- as.numeric(stringr::str_extract(string = test_dates,
                                          pattern = "^\\d+"))

days <- as.numeric(gsub(pattern = "\\.",
                        replacement = "",
                        x = stringr::str_extract(string = test_dates,
                                                 pattern = "\\.\\d+\\.")))

years <- 2000 + as.numeric(gsub(pattern = "\\.",
                                replacement = "",
                                x = stringr::str_extract(string = test_dates,
                                                         pattern = "\\.\\d+$")))

# Преобразуем их к единому формату дат
date_time <- ISOdate(year = years, month = months, day = days)
date <- as.Date(date_time)

# Удаление переменных
rm("months", "days", "years", "test_dates", "date_time")

# 2. Транспонирование данных и приведение к новой таблице на основе исходной
# Измерения в исходном фрейме начинаются с 4 столбца, следовательно
# сделаем выборку всех строк по столбцам с 4 по последний и транспонируем,
# поскольку в пределах данного куска таблицы все данные однотипны
new_table <- data.frame(date = date,
                        t(as.matrix(df[,4:ncol(df)])),
                        row.names = 1:(ncol(df) - 3))
new_table_deaths <- data.frame(date = date,
                               t(as.matrix(df_deaths[,4:ncol(df_deaths)])),
                               row.names = 1:(ncol(df_deaths) - 3))
new_table_recovered <- data.frame(date = date,
                                  t(as.matrix(df_recovered[,4:ncol(df_recovered)])),
                                  row.names = 1:(ncol(df_recovered) - 3))

colnames(new_table) <- c("date", country_names)
colnames(new_table_deaths) <- c("date", country_names_deaths)
colnames(new_table_recovered) <- c("date", country_names_recovered)

# Экспорт -----------------------------------------------------------------
# Экспортируем подготовленные данные в csv-файл
if (!dir.exists("output_csv")) {
  dir.create("output_csv")
}
write.csv(x = new_table,
          file = "output_csv/data_conf_output.csv")
write.csv(x = df_meta,
          file = "output_csv/metadata_conf.csv")
write.csv(x = new_table_deaths,
          file = "output_csv/data_deaths_output.csv")
write.csv(x = df_deaths_meta,
          file = "output_csv/metadata_deaths.csv")
write.csv(x = new_table_recovered,
          file = "output_csv/data_recovered_output.csv")
write.csv(x = df_recovered_meta,
          file = "output_csv/metadata_recovered.csv")


# Экспортируем данные в xlsx
if (!dir.exists("output_xlsx")) {
  dir.create("output_xlsx")
}
openxlsx::write.xlsx(x = new_table,
                     file = "output_xlsx/data_conf_output.xlsx")
openxlsx::write.xlsx(x = df_meta,
                     file = "output_xlsx/metadata_conf.xlsx")
openxlsx::write.xlsx(x = new_table_deaths,
                     file = "output_xlsx/data_deaths_output.xlsx")
openxlsx::write.xlsx(x = df_deaths_meta,
                     file = "output_xlsx/metadata_deaths.xlsx")
openxlsx::write.xlsx(x = new_table_recovered,
                     file = "output_xlsx/data_recovered_output.xlsx")
openxlsx::write.xlsx(x = df_recovered_meta,
                     file = "output_xlsx/metadata_recovered.xlsx")


# Удаление данных сессии --------------------------------------------------
rm(list = ls())

library(dplyr)
library(ggplot2)
library(forecast)

# Импорт подтверждённых заболеваний -------------------------------------------
df_confirmed <- read.csv("./output_csv/data_conf_output.csv")
df_confirmed$date <- as.Date(df_confirmed$date)
df_confirmed$World <- rowSums(df_confirmed[, 3:ncol(df_confirmed)])

# Импорт выздоровлений --------------------------------------------------------
df_recovered <- read.csv("./output_csv/data_recovered_output.csv")
df_recovered$date <- as.Date(df_recovered$date)
df_recovered$World <- rowSums(df_recovered[, 3:ncol(df_recovered)])

# Импорт смертей --------------------------------------------------------------
df_deaths <- read.csv("./output_csv/data_deaths_output.csv")
df_deaths$date <- as.Date(df_deaths$date)
df_deaths$World <- rowSums(df_deaths[, 3:ncol(df_deaths)])
```

```{r Egypt_Belarus, echo = F, out.height=800, out.width=800, dpi = 512}
df1 <- select(df_confirmed, contains("Egypt"))[-(1:70), ]
df2 <- select(df_confirmed, contains("Belarus"))[-(1:70), ]

corr_1 = cor((diff(df1)), (diff(df2)))
plot(y = (log(diff(df1))), 
     x = 1:length((log(diff(df1)))), 
     type = "o", 
     col = "blue",
     lty = 2,
     lwd = I(0.5),
     cex = I(0.5),
     pch = 19,
     main = corr_1)
par(new = TRUE)
plot(y = (log(diff(df2))), 
     x = 1:length((log(diff(df2)))), 
     type = "o",
     lty = 2,
     lwd = I(0.5),
     cex = I(0.5),
     pch = 19,
     col = "red", 
     axes = FALSE)
axis(4, ylim = c(0,7000), 
     col = "red", col.axis = "red", 
     las = 1)
legend(x = 10, y = 0.9, legend = c("Egypt", "Belarus"),
       col = c("blue", "red"), lty = c(1, 1))
abline(h = c(min((log(diff(df2)))),
             max((log(diff(df2))))),
       col = "red", lty = 2, lwd = I(0.5))
abline(h = c(min((log(diff(df1)))),
             max((log(diff(df1))))),
       col = "blue", lty = 2, lwd = I(0.5))
abline(v = 80)
abline(v = 272)


plot(y = (log(diff(df1))),
     x = (log(diff(df2))),
     type = "o",
     ylab = "log(Egypt)",
     xlab = paste0("log(Belarus)"),
     pch = 19,
     lty = 2,
     lwd = I(0.5))
abline(v = c(min((log(diff(df2)))),
             max((log(diff(df2))))),
       col = "red", lty = 2, lwd = I(0.5))
abline(h = c(min((log(diff(df1)))),
             max((log(diff(df1))))),
       col = "blue", lty = 2, lwd = I(0.5))
radius_a = 0.9
radius_b = 1.2
center = 6
points(x = c(center - radius_a, center, center + radius_a, center, center) - 0.1, 
       y = c(center, center, center, center + radius_b, center - radius_b), pch = 19, cex = I(3), col = "red")

par(mfrow = c(1, 1))
```

```{r Egypt_Belarus lagged, echo = F, out.height=800, out.width=800, dpi = 512}
lag = 35

corr_1 = cor((diff(df1)), (diff(df2)))

plot(y = (log(diff(df1))), 
     x = 1:length((log(diff(df1)))), 
     type = "o", 
     col = "blue",
     lty = 2,
     lwd = I(0.5),
     cex = I(0.5),
     pch = 19,
     main = corr_1)
lines(y = (log(diff(df2))), 
     x = 1:length((log(diff(df2)))) + lag, 
     type = "o",
     lty = 2,
     lwd = I(0.5),
     cex = I(0.5),
     pch = 19,
     col = "red")
legend(x = 10, y = 0.9, legend = c("Egupt", "Belarus"),
       col = c("blue", "red"), lty = c(1, 1))
abline(h = c(min((log(diff(df2)))),
             max((log(diff(df2))))),
       col = "red", lty = 2, lwd = I(0.5))
abline(h = c(min((log(diff(df1)))),
             max((log(diff(df1))))),
       col = "blue", lty = 2, lwd = I(0.5))


plot(y = (log(diff(df1[-(1:30)]))),
     x = (log(diff(df2[-((length(df2) - 29):length(df2))]))),
     type = "o",
     ylab = "log(Egypt)",
     xlab = paste0("log(Belarus)"),
     pch = 19,
     lty = 2,
     lwd = I(0.5))
abline(v = c(min((log(diff(df2)))),
             max((log(diff(df2))))),
       col = "red", lty = 2, lwd = I(0.5))
abline(h = c(min((log(diff(df1)))),
             max((log(diff(df1))))),
       col = "blue", lty = 2, lwd = I(0.5))
abline(a = 0.5, b = 0.8, col = "red")
abline(a = 1.5, b = 0.8, col = "blue")
par(mfrow = c(1, 1))
```



```{r}
plot(x = cumsum(c(0, log(diff(df2)))),
     y = c(0, log(diff(df1))) / cumsum(c(0, log(diff(df1)))),
     ylim = c(0, 0.07),
     xlab = "Belarus",
     ylab = "dEgypt_dt / Egypt",
     main = "X накопленные значения")
abline(a = 0.09, b = -0.00031, col = "red")
text(x = 300, y = 0.045, label = "alpha_red = -0.00031")
text(x = 300, y = 0.042, label = "beta_red = 0.09")

alpha_X_red <- -0.00031
beta_X_red <- 0.09

abline(a = 0.0355, b = -0.0000385, col = "blue")
text(x = 600, y = 0.025, label = "alpha_blue = -0.0000385")
text(x = 600, y = 0.022, label = "beta_blue = 0.0355")

alpha_X_blue <- -0.0000385
beta_X_blue <- 0.0355
```




```{r}
plot(x = cumsum(c(0, log(diff(df1) + 1))),
     y = c(0, log(diff(df2) + 1)) / cumsum(c(0, log(diff(df2) + 1))),
     ylim = c(0, 0.01), 
     xlab = "Egypt",
     ylab = "dBelarus_dt / Belarus",
     main = "Y накопленные значения")
abline(a = 0.0183, b = - 0.0000153, col = "red")
text(x = 1000, y = 0.008, label = "alpha_red = -0.0000153")
text(x = 1000, y = 0.0077, label = "beta_red = 0.0183")

alpha_Y_red <- -0.0000153
beta_Y_red <- 0.0183

abline(a = 0.0088, b = -0.0000027, col = "blue")
text(x = 1525, y = 0.006, label = "alpha_blue = -0.0000027")
text(x = 1525, y = 0.0057, label = "beta_blue = 0.0088")

alpha_Y_blue <- -0.0000027
beta_Y_blue <- 0.0088

abline(a = 0.00513, b = -0.000001, col = "green")
text(x = 2125, y = 0.004, label = "alpha_green = -0.000001")
text(x = 2125, y = 0.0037, label = "beta_green = 0.00513")

alpha_Y_green <- -0.000001
beta_Y_green <- 0.00513
```

```{r}
differential <- function(x) {
  return((x[-(1:2)] - x[-((length(x) - 1):length(x))]) / 2)
}
```



```{r}
S_x = cumsum(c(0, log(diff(df1) + 1)))
S_y = cumsum(c(0, log(diff(df2) + 1)))

S_x_dx <- S_x * (beta_X_blue - alpha_X_blue * S_y)
S_y_dy <- S_y * (beta_Y_green - alpha_Y_green * S_x)
```




```{r}
plot(x = 1:length(df1), y = c(0, log(diff(df1) + 1)), 
     col = "red", 
     main = "Заболеваемость в Египте, реальная и моделируемая",
     pch = 19,
     type = "o",
     lwd = I(0.5), 
     cex = I(0.5), 
     ylim = c(1, 10),
     ylab = "Полулогарифм заболеваемости каждый день",
     xlab = "Даты с ")
lines((diff(S_x_dx)) * 6, 
      col = "blue", 
      type = "o", 
      pch = 19,
      cex = I(0.5),
      lwd = I(0.5))
legend(x = 0, y = 10, 
       legend = c("Реальная заболеваемость", "Моделируемая заболеваемость"), 
       col = c("red", "blue"), 
       lty = c(1, 1), 
       pch = c(19, 19))
```

```{r}
a <- 0.0035
b <- 0
plot((diff(S_x_dx) - a * (1:length(diff(S_x_dx))) - b) * 10 + 5, type = "l", col = "blue")
lines(log(diff(df1) + 1), col = "red")
```

```{r}
plot(x = 1:length(df2), y = c(0, log(diff(df2) + 1)), 
     col = "red", 
     main = "Заболеваемость в Беларуси, реальная и моделируемая",
     pch = 19,
     type = "o",
     lwd = I(0.5), 
     cex = I(0.5), 
     ylim = c(3.5, 9),
     ylab = "Полулогарифм заболеваемости каждый день",
     xlab = "Даты с ")
lines((diff(S_y_dy) + 0.0165) * 100, 
      col = "blue", 
      type = "o", 
      pch = 19,
      cex = I(0.5),
      lwd = I(0.5))
legend(x = 0, y = 9, 
       legend = c("Реальная заболеваемость", "Моделируемая заболеваемость"), 
       col = c("red", "blue"), 
       lty = c(1, 1), 
       pch = c(19, 19))
```

```{r}
plot(x = 1:length(df2), y = c(0, log(diff(df2) + 1)), 
     col = "red", 
     main = "Заболеваемость в Беларуси, реальная и моделируемая",
     pch = 19,
     type = "o",
     lwd = I(0.5), 
     cex = I(0.5), 
     ylim = c(3.5, 9),
     ylab = "Полулогарифм заболеваемости каждый день",
     xlab = "Даты с ")
lines(((diff(S_y_dy) + 0.0165) * 100) - 4 - 0.75 * 10e-03 * 1:length(diff(S_y_dy)) + 5.5, 
      col = "blue", 
      type = "o", 
      pch = 19,
      cex = I(0.5),
      lwd = I(0.5))
legend(x = 0, y = 9, 
       legend = c("Реальная заболеваемость", "Моделируемая заболеваемость"), 
       col = c("red", "blue"), 
       lty = c(1, 1), 
       pch = c(19, 19))
```


```{r}
plot((diff(S_x_dx) - a * (1:length(diff(S_x_dx))) - b) * 10 + 5, 
     type = "o",
     pch = 19, 
     lwd = I(0.5),
     cex = I(0.5),
     col = "red",
     ylim = c(4, 8))
lines(((diff(S_y_dy) + 0.0165) * 100) - 4 - 0.75 * 10e-03 * 1:length(diff(S_y_dy)) + 5.5,
      type = "o",
      pch = 19,
      lwd = I(0.5),
      cex = I(0.5),
      col = "blue")

plot(x = (diff(S_x_dx) - a * (1:length(diff(S_x_dx))) - b) * 10 + 5, 
     y = ((diff(S_y_dy) + 0.0165) * 100) - 4 - 0.75 * 10e-03 * 1:length(diff(S_y_dy)) + 5.5,
     xlim = c(4, 8),
     ylim = c(4, 8))
radius_a = 1.3
radius_b = 0.8
center_x = 6.15
center_y = 6.3
points(x = c(center_x - radius_a, center_x, center_x + radius_a, center_x, center_x) - 0.1, 
       y = c(center_y, center_y, center_y, center_y + radius_b, center_y - radius_b), pch = 19, cex = I(3), col = "red")
```

```{r}
df1 <- select(df_confirmed, contains("Egypt"))[, ]
df2 <- select(df_confirmed, contains("Russia"))[, ]
```

```{r}
plot(log(diff(df1)))
plot(log(diff(df2)))

plot(log(diff(df1)), ylim = c(3, 11))
lines(log(diff(df2)))
```


```{r}
S_x = cumsum(c(0, log(diff(df1) + 1)))
S_y = cumsum(c(0, log(diff(df2) + 1)))

S_x_dx <- S_x * (beta_X_blue - alpha_X_blue * S_y)
S_y_dy <- S_y * (beta_Y_green - alpha_Y_green * S_x)
```


```{r}
a <- 0.005
b <- 0

plot((diff(S_x_dx) - a * (1:length(diff(S_x_dx))) - b) * 10 + 5, 
     type = "o",
     pch = 19, 
     lwd = I(0.5),
     cex = I(0.5),
     col = "red",
     ylim = c(1, 9))
lines(((diff(S_y_dy) + 0.0165) * 100) - 4 - 1.3 * 10e-03 * 1:length(diff(S_y_dy)) + 5.5,
      type = "o",
      pch = 19,
      lwd = I(0.5),
      cex = I(0.5),
      col = "blue")

plot(x = (diff(S_x_dx) - a * (1:length(diff(S_x_dx))) - b) * 10 + 5, 
     y = ((diff(S_y_dy) + 0.0165) * 100) - 4 - 1.3 * 10e-03 * 1:length(diff(S_y_dy)) + 5.5,
     xlim = c(1, 5),
     ylim = c(6, 7.5))
```
